GET http://localhost:3000

###

GET http://localhost:3000/admin/login

###

POST http://localhost:3000/admin/login
Content-Type: : application/json

{
    "username" : "admin",
    "password" : "admin123"
}

###
GET http://localhost:3000/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxLCJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6IiQyYSQxMCQ2NUpMcUVLZGY3MThoQUc3Mk55TDNPRmFnY1JMUU00djZ5SmtJUTBTbU5iMWRTUTJGbzFMdSJ9LCJpYXQiOjE2NTEwMzc5MDd9._odC2kTwT2l06dXkpL1zK7sJLMxd0C3XQPcQnUit7fk

###